global:
  values:
    public: true
    release:
      draft: true
    ytt:
      template_paths: remote/ytt
  workflows:
    - file: library.yml
    - file: pr.yml
    - file: publish.yml
    - file: workflow-generator.yml
